# Generated by Django 4.2.5 on 2023-09-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, unique=True, verbose_name="Team Name")),
                ("wins", models.IntegerField(blank=True, default=0, null=True)),
                ("draws", models.IntegerField(blank=True, default=0, null=True)),
                ("loses", models.IntegerField(blank=True, default=0, null=True)),
                ("points", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_team_score", models.PositiveIntegerField()),
                ("second_team_score", models.PositiveIntegerField()),
                (
                    "first_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_team_results",
                        to="sports_league_app.team",
                    ),
                ),
                (
                    "second_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_team_results",
                        to="sports_league_app.team",
                    ),
                ),
            ],
        ),
    ]
